name: Push To Release Branch

on:
  push:
    branches:
      - release
    paths-ignore:
      - README.md

jobs:
  verify-syntax:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install required modules
        uses: pip install -r requirements.txt

      - name: Run Tests
        uses: python -m unittest tests/*.py
